title: Web Development Training
description: A guide to web development covering HTML, CSS, JavaScript, and Django.
baseurl: "/webdev-training"
url: "https://mikeh74.github.io/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

nav:
  - title: Home
    url: /
  - title: Intro to Web
    url: /intro-to-web
  - title: Job Roles
    url: /job-roles
  - title: HTML 101
    url: /html-101
  - title: CSS 101
    url: /css-101
  - title: JavaScript 101
    url: /javascript-101
  - title: Django
    url: /django/intro
    children:
      - title: Introduction
        url: /django/intro
      - title: File Structure
        url: /django/file_structure
      - title: Routing
        url: /django/routing
      - title: Models
        url: /django/models
      - title: Views
        url: /django/views
      - title: Resources
        url: /django/resources

exclude:
  - README.md
